---
# tasks file for threadedbiobench
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  become: yes

- name: Reboot immediately
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  become: yes

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Install EPEL
  yum:
    name: epel-release
    state: latest
    disable_gpg_check: 1
  become: yes

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present
    disable_gpg_check: 1
  become: yes


- name: Install packages
  with_items: "{{ common_packages | mandatory }}"
  yum:
    name: "{{ item }}"
    state: latest
    disable_gpg_check: 1
  become: yes

- name: Install R - packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://ftp.heanet.ie/mirrors/cran.r-project.org/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - grid
    - gridExtra
    - RColorBrewer
    - stringr

- name: Create empty benchmark output directory
  file:
    path: /home/centos/benchmark_output/
    state: directory

- name: Create empty dataset directory
  file:
    path: /home/centos/datasets/
    state: directory

- name: Create empty 1000 genomes directory
  file:
    path: /home/centos/datasets/1000_genomes
    state: directory

- name: Create empty tensorflow data directory
  file:
    path: /home/centos/datasets/tensorflow
    state: directory

- name: Create empty gromacs data directory
  file:
    path: /home/centos/datasets/gromacs
    state: directory

- name: Create empty results directory
  file:
    path: /home/centos/results
    state: directory



- name: Download read set ERR016155
  get_url:
    url: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00125/sequence_read/ERR016155.filt.fastq.gz
    dest: /home/centos/datasets/1000_genomes/ERR016155.filt.fastq.gz

- name: Unarchive read set ERR016155
  command: gunzip /home/centos/datasets/1000_genomes/ERR016155.filt.fastq.gz creates=/home/centos/datasets/1000_genomes/ERR016155.filt.fastq

- name: Download read set ERR251006
  get_url:
    url: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00110/sequence_read/ERR251006.filt.fastq.gz
    dest: /home/centos/datasets/1000_genomes/ERR251006.filt.fastq.gz

- name: Unarchive read set ERR251006
  command: gunzip /home/centos/datasets/1000_genomes/ERR251006.filt.fastq.gz creates=/home/centos/datasets/1000_genomes/ERR251006.filt.fastq

- name: Download reference genome GRCh38
  get_url: 
    url: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
    dest: /home/centos/datasets/1000_genomes/GRCh38_full_analysis_set_plus_decoy_hla.fa

- name: Download and unarchive tensorflow models
  unarchive:
    src: https://s3.denbi.uni-tuebingen.de/fb-test/tf_benchmark/models.tar.gz
    dest: /home/centos/datasets/tensorflow/
    remote_src: yes

- name: Download and unarchive tensorflow cifar-10-binary
  unarchive:
    src: https://s3.denbi.uni-tuebingen.de/fb-test/tf_benchmark/cifar-10-binary.tar.gz
    dest: /home/centos/datasets/tensorflow/
    remote_src: yes

- name: Download tensorflow cifar-10-binary again, needs to be present as .tar.gz
  get_url:
    url: https://s3.denbi.uni-tuebingen.de/fb-test/tf_benchmark/cifar-10-binary.tar.gz
    dest: /home/centos/datasets/tensorflow/


- name: Download and unarchive GROMACS dataset
  unarchive:
    src: ftp://ftp.gromacs.org/pub/benchmarks/ADH_bench_systems.tar.gz
    dest: /home/centos/datasets/gromacs/
    remote_src: yes

- name: Set nsteps value from 10000 to 50000 in 
  command: sed -i 's/nsteps.*/nsteps                  = 50000/' /home/centos/datasets/gromacs/adh_cubic/pme_verlet.mdp

- name: Create empty bowtie2 directory
  file:
    path: /home/centos/bowtie2/
    state: directory

- name: Create empty bowtie2 output directory
  file:
    path: /home/centos/benchmark_output/bowtie2/
    state: directory

- name: Download and unarchive bowtie2 tool
  unarchive:
    src: https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.4.2/bowtie2-2.3.4.2-source.zip
    dest: /home/centos/bowtie2/
    remote_src: yes
    creates: /home/centos/bowtie2/*

- make:
    chdir: /home/centos/bowtie2/bowtie2-2.3.4.2/
    target: static-libs

- make:
    chdir: /home/centos/bowtie2/bowtie2-2.3.4.2/
    target: all
    params:
      STATIC_BUILD: 1

- name: Create empty velvet directory
  file:
    path: /home/centos/velvet/
    state: directory

- name: Create empty velvet output directory
  file:
    path: /home/centos/benchmark_output/velvet/
    state: directory

- name: Download velvet from git repo
  command: git clone https://github.com/dzerbino/velvet.git /home/centos/velvet/ creates=/home/centos/velvet/*

- name: Compile and install velvet
  make: 
    chdir: /home/centos/velvet/
    params:
      OPENMP: 1

- name: Create empty IDBA directory
  file:
    path: /home/centos/IDBA/
    state: directory

- name: Create empty IDBA output directory
  file:
    path: /home/centos/benchmark_output/IDBA/
    state: directory

- name: Download and unarchive IDBA tool in version 1.0.9
  unarchive:
    src: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/hku-idba/idba_ud-1.0.9.tar.gz
    dest: /home/centos/IDBA/
    remote_src: yes
    creates: /home/centos/IDBA/*

- name: Configure IDBA
  command: ./configure
  args:
    chdir: /home/centos/IDBA/idba_ud-1.0.9/

- name: Compile and install IDBA
  make:
    chdir: /home/centos/IDBA/idba_ud-1.0.9/

- name: Create empty tensorflow directory
  file:
    path: /home/centos/tensorflow/
    state: directory

- name: Create empty tensorflow output directory
  file:
    path: /home/centos/benchmark_output/tensorflow/
    state: directory

- name: Use pip install to install pip in Version 9.0.3
  pip:
    name: pip
    version: 9.0.3
    state: forcereinstall
  become: yes

- name: Use pip install to install tensorflow in version 1.4.0
  pip:
    name: tensorflow
    version: 1.4.0
  become: yes

- name: Create empty GROMACS directory
  file:
    path: /home/centos/gromacs/
    state: directory

- name: Create empty GROMACS output directory
  file:
    path: /home/centos/benchmark_output/gromacs/
    state: directory

- name: Create empty GROMACS build directory
  file:
    path: /home/centos/gromacs/gromacs-2018.3/build/
    state: directory

- name: Download and unarchive GROMACS 2018.3
  unarchive:
    src: ftp://ftp.gromacs.org/pub/gromacs/gromacs-2018.3.tar.gz
    dest: /home/centos/gromacs/
    remote_src: yes
    creates: /home/centos/gromacs/*

- name: Prepare makefile for GROMACS with cmake3
  command:  chdir=/home/centos/gromacs/gromacs-2018.3/build/ cmake3 -DGMX_BUILD_OWN_FFTW=on -DGMX_GPU=off -DGMX_BUILD_MPI=off /home/centos/gromacs/gromacs-2018.3/

- name: Compile GROMACS
  make:
    chdir: /home/centos/gromacs/gromacs-2018.3/build/
    target: all

- name: Install GROMACS
  make:
    chdir: /home/centos/gromacs/gromacs-2018.3/build/
    target: install
  become: yes

- name: Build input files for GROMACS on testdata adh_cubic
  command: /usr/local/gromacs/bin/gmx grompp -f /home/centos/datasets/gromacs/adh_cubic/pme_verlet.mdp -c /home/centos/datasets/gromacs/adh_cubic/conf.gro -p /home/centos/datasets/gromacs/adh_cubic/topol.top -o /home/centos/datasets/gromacs/adh_cubic/topol -po /home/centos/datasets/gromacs/adh_cubic/mdout

- name: Create empty SPAdes directory
  file:
    path: /home/centos/SPAdes/
    state: directory

- name: Create empty SPAdes output directory
  file:
    path: /home/centos/benchmark_output/SPAdes/
    state: directory

- name: Download and unarchive SPAdes 3.12.0
  unarchive:
    src: http://cab.spbu.ru/files/release3.12.0/SPAdes-3.12.0-Linux.tar.gz
    dest: /home/centos/SPAdes/
    remote_src: yes

- name: Convert fastq to fasta data (ERR016155)
  command: /home/centos/IDBA/idba_ud-1.0.9/bin/fq2fa /home/centos/datasets/1000_genomes/ERR016155.filt.fastq /home/centos/datasets/1000_genomes/ERR016155.filt.fa

- name: Convert fastq to fasta data (ERR251006)
  command: /home/centos/IDBA/idba_ud-1.0.9/bin/fq2fa /home/centos/datasets/1000_genomes/ERR251006.filt.fastq /home/centos/datasets/1000_genomes/ERR251006.filt.fa

